version: '3'

services:
  db:
    build:
      context: .
      dockerfile: Dockerfile_db
    container_name: database_container
    volumes:
      - ./database.db:/app/database.db

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: webapp_container
    ports:
      - "5000:5000"
    depends_on:
      - db
    volumes:
      - .:/app
